drssr:
  port: ':3001'

redis:
  address: 'localhost:6379'
  password: ''
  db_name: 0

postgres:
  host: "localhost"
  port: "5432"
  user: "admin"
  pass: "lolkek"
  name: "drssr"

cutter:
  url: 'http://127.0.0.1:5001'
  timeout: 10s

classifier:
  url: 'localhost:5002'

similarity:
  url: 'http://127.0.0.1:5001'
  timeout: 10s

well_similarity_percent: 50
expiration_cookie_time": 1382400
