drssr:
  port: ':3001'

redis:
  address: '127.0.0.1:6379'
  # address: 'host.docker.internal:6379'
  password: ''
  db_name: 0

postgres:
  host: "95.84.192.140"
  # host: "host.docker.internal"
  port: "5432"
  user: "admin"
  pass: "lolkek"
  name: "drssr"

cutter:
  url: 'http://127.0.0.1:5001'
  # url: 'http://host.docker.internal:5001'
  timeout: 10s

classifier:
  url: '127.0.0.1:5002'
  # url: 'host.docker.internal:5002'

similarity:
  url: 'http://127.0.0.1:5001'
  # url: 'http://host.docker.internal:5001'
  timeout: 10s

tg_bot_stylist_accept:
  api_token: 5813757508:AAEAqeRBEU2P4G3Az_OV77hLguQrUoIqH0Y
  admin_chat_id: -847172576
  email_notifications: false

mailer:
  email: inagdimaev@mail.ru
  password: v6WYwwxm4F3Kh7h0DSPe

well_similarity_percent: 50
expiration_cookie_time": 1382400
