// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5a72dc82DecodeDrssrInternalModels(in *jlexer.Lexer, out *Post) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "type":
			out.Type = PostType(in.String())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Desc = string(in.String())
		case "creator_id":
			out.CreatorID = uint64(in.Uint64())
		case "element_id":
			out.ElementID = uint64(in.Uint64())
		case "clothes":
			(out.Clothes).UnmarshalEasyJSON(in)
		case "look":
			(out.Look).UnmarshalEasyJSON(in)
		case "previews":
			if in.IsNull() {
				in.Skip()
				out.Previews = nil
			} else {
				in.Delim('[')
				if out.Previews == nil {
					if !in.IsDelim(']') {
						out.Previews = make([]string, 0, 4)
					} else {
						out.Previews = []string{}
					}
				} else {
					out.Previews = (out.Previews)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Previews = append(out.Previews, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "previews_paths":
			if in.IsNull() {
				in.Skip()
				out.PreviewsPaths = nil
			} else {
				in.Delim('[')
				if out.PreviewsPaths == nil {
					if !in.IsDelim(']') {
						out.PreviewsPaths = make([]string, 0, 4)
					} else {
						out.PreviewsPaths = []string{}
					}
				} else {
					out.PreviewsPaths = (out.PreviewsPaths)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.PreviewsPaths = append(out.PreviewsPaths, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "likes":
			out.Likes = int(in.Int())
		case "is_liked":
			out.IsLikes = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a72dc82EncodeDrssrInternalModels(out *jwriter.Writer, in Post) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Desc))
	}
	{
		const prefix string = ",\"creator_id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CreatorID))
	}
	{
		const prefix string = ",\"element_id\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ElementID))
	}
	if true {
		const prefix string = ",\"clothes\":"
		out.RawString(prefix)
		(in.Clothes).MarshalEasyJSON(out)
	}
	if true {
		const prefix string = ",\"look\":"
		out.RawString(prefix)
		(in.Look).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"previews\":"
		out.RawString(prefix)
		if in.Previews == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Previews {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"previews_paths\":"
		out.RawString(prefix)
		if in.PreviewsPaths == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.PreviewsPaths {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"likes\":"
		out.RawString(prefix)
		out.Int(int(in.Likes))
	}
	{
		const prefix string = ",\"is_liked\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsLikes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Post) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a72dc82EncodeDrssrInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Post) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a72dc82EncodeDrssrInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Post) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a72dc82DecodeDrssrInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Post) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a72dc82DecodeDrssrInternalModels(l, v)
}
func easyjson5a72dc82DecodeDrssrInternalModels1(in *jlexer.Lexer, out *LikesStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "likes":
			out.Likes = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a72dc82EncodeDrssrInternalModels1(out *jwriter.Writer, in LikesStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"likes\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Likes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LikesStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a72dc82EncodeDrssrInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LikesStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a72dc82EncodeDrssrInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LikesStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a72dc82DecodeDrssrInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LikesStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a72dc82DecodeDrssrInternalModels1(l, v)
}
func easyjson5a72dc82DecodeDrssrInternalModels2(in *jlexer.Lexer, out *ArrayPosts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ArrayPosts, 0, 0)
			} else {
				*out = ArrayPosts{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v7 Post
			(v7).UnmarshalEasyJSON(in)
			*out = append(*out, v7)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a72dc82EncodeDrssrInternalModels2(out *jwriter.Writer, in ArrayPosts) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ArrayPosts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a72dc82EncodeDrssrInternalModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ArrayPosts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a72dc82EncodeDrssrInternalModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ArrayPosts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a72dc82DecodeDrssrInternalModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ArrayPosts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a72dc82DecodeDrssrInternalModels2(l, v)
}
